In [ ]:
#Importing Libraries

In [175]:
import numpy as np 

In [176]:
import matplotlib.pyplot as plt

In [177]:
import pandas as pd

In [178]:
import os

In [ ]:
#Setting Present Working Directory

In [274]:
os.getcwd()

'D:\\Machine Learning A-Z Template Folder\\Part 2 - Regression\\Section 4 - Simple Linear Regression\\Simple_Linear_Regression'

In [273]:
os.chdir("D:\\Machine Learning A-Z Template Folder\\Part 2 - Regression\\Section 4 - Simple Linear Regression\\Simple_Linear_Regression")

In [182]:
#Importing the dataset

In [570]:
dataset = pd.read_csv('Salary_Data.csv',index_col ="Sno")

In [ ]:
#Dividing Dependent and Independent Variables.

In [571]:
dataset

YearsExperience    Salary
Sno                           
1                1.1   39343.0
2                1.3   46205.0
3                1.5   37731.0
4                2.0   43525.0
5                2.2   39891.0
6                2.9   56642.0
7                3.0   60150.0
8                3.2   54445.0
9                3.2   64445.0
10               3.7   57189.0
11               3.9   63218.0
12               4.0   55794.0
13               4.0   56957.0
14               4.1   57081.0
15               4.5   61111.0
16               4.9   67938.0
17               5.1   66029.0
18               5.3   83088.0
19               5.9   81363.0
20               6.0       NaN
21               6.8   91738.0
22               7.1   98273.0
23               7.9  101302.0
24               8.2  113812.0
25               8.7  109431.0
26               9.0  105582.0
27               9.5  116969.0
28               9.6  112635.0
29              10.3  122391.0
30              10.5  121872.0

In [572]:
X = dataset.iloc[:, :-1].values

In [536]:
X


array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [573]:
y = dataset.iloc[:, 1].values

In [538]:
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,     nan,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [539]:
?y

In [411]:
y.reshape(1,-1)

array([[ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
         54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
         61111.,  67938.,  66029.,  83088.,  81363.,     nan,  91738.,
         98273., 101302., 113812., 109431., 105582., 116969., 112635.,
        122391., 121872.]])

In [574]:
# Taking care of missing data
from sklearn.impute import SimpleImputer
#Sklearn is actually scikit learn is a free ML Library for Python.
#SimpleImputer is a class which take cares of missing data in dataset

In [453]:
#Here we are creating the object instance of the class
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

In [327]:
help(imputer.fit)

Help on method fit in module sklearn.impute:

fit(X, y=None) method of sklearn.impute.SimpleImputer instance
    Fit the imputer on X.
    
    Parameters
    ----------
    X : {array-like, sparse matrix}, shape (n_samples, n_features)
        Input data, where ``n_samples`` is the number of samples and
        ``n_features`` is the number of features.
    
    Returns
    -------
    self : SimpleImputer



In [387]:
print(dataset)

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0       NaN
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0


In [461]:
#fits data on which we want to act the imputer.
#  X : {array-like, sparse matrix}, shape (n_samples, n_features)
#  Input data, where n_samples is the number of samples and n_features is the number of features.
# As we dont know samples we are taking at as -1, and we know it is only one feature(Salary)
imputer=imputer.fit(y.reshape(-1,1))

In [462]:
#Transform is the function used to replace missing data with the given strategy 
y = imputer.transform(y.reshape(-1,1))

In [463]:
#MEAN 75384.48275862
y,dataset

(array([[ 39343.        ],
        [ 46205.        ],
        [ 37731.        ],
        [ 43525.        ],
        [ 39891.        ],
        [ 56642.        ],
        [ 60150.        ],
        [ 54445.        ],
        [ 64445.        ],
        [ 57189.        ],
        [ 63218.        ],
        [ 55794.        ],
        [ 56957.        ],
        [ 57081.        ],
        [ 61111.        ],
        [ 67938.        ],
        [ 66029.        ],
        [ 83088.        ],
        [ 81363.        ],
        [ 75384.48275862],
        [ 91738.        ],
        [ 98273.        ],
        [101302.        ],
        [113812.        ],
        [109431.        ],
        [105582.        ],
        [116969.        ],
        [112635.        ],
        [122391.        ],
        [121872.        ]]),     YearsExperience    Salary
 0               1.1   39343.0
 1               1.3   46205.0
 2               1.5   37731.0
 3               2.0   43525.0
 4               2.2   39891.0
 5 

In [341]:
imputer2 = SimpleImputer(missing_values = np.nan, strategy = 'median')

In [342]:
imputer2=imputer2.fit(y.reshape(-1,1))

In [343]:
y = imputer2.transform(y.reshape(-1,1))

In [344]:
y

array([[ 39343.],
       [ 46205.],
       [ 37731.],
       [ 43525.],
       [ 39891.],
       [ 56642.],
       [ 60150.],
       [ 54445.],
       [ 64445.],
       [ 57189.],
       [ 63218.],
       [ 55794.],
       [ 56957.],
       [ 57081.],
       [ 61111.],
       [ 67938.],
       [ 66029.],
       [ 83088.],
       [ 81363.],
       [ 64445.],
       [ 91738.],
       [ 98273.],
       [101302.],
       [113812.],
       [109431.],
       [105582.],
       [116969.],
       [112635.],
       [122391.],
       [121872.]])

In [370]:
imputer3 = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')

In [371]:
imputer3=imputer3.fit(y.reshape(-1,1))

In [372]:
y = imputer3.transform(y.reshape(-1,1))

In [373]:
y

array([[ 39343.],
       [ 46205.],
       [ 37731.],
       [ 43525.],
       [ 39891.],
       [ 56642.],
       [ 60150.],
       [ 54445.],
       [ 64445.],
       [ 57189.],
       [ 63218.],
       [ 55794.],
       [ 56957.],
       [ 57081.],
       [ 61111.],
       [ 67938.],
       [ 66029.],
       [ 83088.],
       [ 81363.],
       [ 37731.],
       [ 91738.],
       [ 98273.],
       [101302.],
       [113812.],
       [109431.],
       [105582.],
       [116969.],
       [112635.],
       [122391.],
       [121872.]])

In [575]:
imputer4 = SimpleImputer(missing_values = np.nan, strategy = 'constant',fill_value=int(y_pred))

In [576]:
imputer4=imputer4.fit(y.reshape(-1,1))

In [577]:
y = imputer4.transform(y.reshape(-1,1))

In [578]:
y

array([[ 39343.],
       [ 46205.],
       [ 37731.],
       [ 43525.],
       [ 39891.],
       [ 56642.],
       [ 60150.],
       [ 54445.],
       [ 64445.],
       [ 57189.],
       [ 63218.],
       [ 55794.],
       [ 56957.],
       [ 57081.],
       [ 61111.],
       [ 67938.],
       [ 66029.],
       [ 83088.],
       [ 81363.],
       [ 82537.],
       [ 91738.],
       [ 98273.],
       [101302.],
       [113812.],
       [109431.],
       [105582.],
       [116969.],
       [112635.],
       [122391.],
       [121872.]])

In [555]:
dataset = pd.read_csv('Salary_Data.csv',index_col ="Sno")

In [556]:
dataset

YearsExperience    Salary
Sno                           
1                1.1   39343.0
2                1.3   46205.0
3                1.5   37731.0
4                2.0   43525.0
5                2.2   39891.0
6                2.9   56642.0
7                3.0   60150.0
8                3.2   54445.0
9                3.2   64445.0
10               3.7   57189.0
11               3.9   63218.0
12               4.0   55794.0
13               4.0   56957.0
14               4.1   57081.0
15               4.5   61111.0
16               4.9   67938.0
17               5.1   66029.0
18               5.3   83088.0
19               5.9   81363.0
20               6.0       NaN
21               6.8   91738.0
22               7.1   98273.0
23               7.9  101302.0
24               8.2  113812.0
25               8.7  109431.0
26               9.0  105582.0
27               9.5  116969.0
28               9.6  112635.0
29              10.3  122391.0
30              10.5  121872.0

In [557]:
dataset2=dataset.drop([20],axis=0)

In [558]:
dataset2

YearsExperience    Salary
Sno                           
1                1.1   39343.0
2                1.3   46205.0
3                1.5   37731.0
4                2.0   43525.0
5                2.2   39891.0
6                2.9   56642.0
7                3.0   60150.0
8                3.2   54445.0
9                3.2   64445.0
10               3.7   57189.0
11               3.9   63218.0
12               4.0   55794.0
13               4.0   56957.0
14               4.1   57081.0
15               4.5   61111.0
16               4.9   67938.0
17               5.1   66029.0
18               5.3   83088.0
19               5.9   81363.0
21               6.8   91738.0
22               7.1   98273.0
23               7.9  101302.0
24               8.2  113812.0
25               8.7  109431.0
26               9.0  105582.0
27               9.5  116969.0
28               9.6  112635.0
29              10.3  122391.0
30              10.5  121872.0

In [559]:
y2 = dataset2.iloc[:, 1].values

In [560]:
X2 = dataset2.iloc[:, :-1].values

In [561]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X2, y2, test_size = 10, random_state = 0)

In [562]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [563]:
y_pred = regressor.predict([[6]])

In [564]:
y_pred

array([82537.52055345])

In [579]:
y

array([[ 39343.],
       [ 46205.],
       [ 37731.],
       [ 43525.],
       [ 39891.],
       [ 56642.],
       [ 60150.],
       [ 54445.],
       [ 64445.],
       [ 57189.],
       [ 63218.],
       [ 55794.],
       [ 56957.],
       [ 57081.],
       [ 61111.],
       [ 67938.],
       [ 66029.],
       [ 83088.],
       [ 81363.],
       [ 82537.],
       [ 91738.],
       [ 98273.],
       [101302.],
       [113812.],
       [109431.],
       [105582.],
       [116969.],
       [112635.],
       [122391.],
       [121872.]])

In [581]:
dataset2.loc[20] = [6.0,int(y_pred)]

In [582]:
dataset2

YearsExperience    Salary
Sno                           
1                1.1   39343.0
2                1.3   46205.0
3                1.5   37731.0
4                2.0   43525.0
5                2.2   39891.0
6                2.9   56642.0
7                3.0   60150.0
8                3.2   54445.0
9                3.2   64445.0
10               3.7   57189.0
11               3.9   63218.0
12               4.0   55794.0
13               4.0   56957.0
14               4.1   57081.0
15               4.5   61111.0
16               4.9   67938.0
17               5.1   66029.0
18               5.3   83088.0
19               5.9   81363.0
21               6.8   91738.0
22               7.1   98273.0
23               7.9  101302.0
24               8.2  113812.0
25               8.7  109431.0
26               9.0  105582.0
27               9.5  116969.0
28               9.6  112635.0
29              10.3  122391.0
30              10.5  121872.0
20               6.0   82537.0